### PR TITLE
starting Auth

### PR DESCRIPTION
**Pull request by ChaozWollf**

### CODE REVIEW

**Review by CrisesAverting — APPROVED** [review]
looks ok

**Comment by CrisesAverting** [comment]
merge approved

**Comment by PeteMcKasty** [comment]
Nicco is it only allowing you to push the merge? I want to pull down and start building out stripe but want to wait until Brandon's updates are merged so I do not have any conflicts

**Comment by ChaozWollf** [comment]
I dont think it matters who approves it, as long as it isnt me.....so if you want to send it thru Peter I think you can

**Comment by ChaozWollf** [comment]
just requires another set of eyes

**Comment by ChaozWollf** [comment]
but then I could be wrong

**Pull request merged**
